---
- name: Install and Configure ELK Stack
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Download Elastic GPG key
      become: yes
      get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: /tmp/GPG-KEY-elasticsearch

    - name: Import Elastic GPG key
      become: yes
      shell: gpg --quiet --no-options --no-default-keyring --secret-keyring /usr/share/keyrings/elasticsearch-keyring.gpg --keyring /usr/share/keyrings/elasticsearch-keyring.gpg --import /tmp/GPG-KEY-elasticsearch

    - name: Install apt-transport-https
      become: yes
      apt:
        name: apt-transport-https
        state: present

    - name: Add Elastic APT repository
      become: yes
      lineinfile:
        dest: /etc/apt/sources.list.d/elastic-8.x.list
        line: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"

    - name: Update apt package cache
      become: yes
      apt:
        update_cache: yes

    - name: Install Elasticsearch, Kibana, and Logstash
      become: yes
      apt:
        name: "{{ item.name }}"
        state: present
      loop:
        - { name: elasticsearch }
        - { name: kibana }
        - name: logstash
          when: "'logstash' not in ansible_facts.packages"  # Install Logstash only if it's not already installed

    - name: Enable and start Elasticsearch service on boot (systemd)
      become: yes
      systemd:
        name: elasticsearch
        enabled: yes
        state: started

    - name: Enable and start Kibana service on boot (systemd)
      become: yes
      systemd:
        name: kibana
        enabled: yes
        state: started

    - name: Enable and start Logstash service on boot (systemd)
      become: yes
      systemd:
        name: logstash
        enabled: yes
        state: started

