---
- name: Instalação do Elasticsearch e Filebeat
  hosts: localhost
  become: yes
  tasks:
    - name: Importar chave GPG do Elasticsearch
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      register: key_result

    - name: Verificar se o arquivo de chave GPG foi importado
      stat:
        path: /usr/share/keyrings/elasticsearch-keyring.gpg
      register: keyfile_result
      when: key_result.changed is defined and key_result.changed

    - name: Importar chave GPG para o arquivo de chave se necessário
      copy:
        content: "{{ lookup('file', '/etc/apt/trusted.gpg.d/elasticsearch-keyring.gpg') }}"
        dest: /usr/share/keyrings/elasticsearch-keyring.gpg
      when: keyfile_result.stat is defined and keyfile_result.stat.exists and key_result.changed

    - name: Instalar apt-transport-https
      apt:
        name: apt-transport-https
        state: present
      when: "'apt-transport-https' not in ansible_facts.packages | default([])"

    - name: Adicionar repositório do Elasticsearch
      block:
        - name: Verificar se o arquivo do repositório existe
          stat:
            path: /etc/apt/sources.list.d/elastic-8.x.list
          register: repo_file_result

        - name: Criar arquivo do repositório
          copy:
            content: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
            dest: /etc/apt/sources.list.d/elastic-8.x.list
          when: repo_file_result.stat is not defined or not repo_file_result.stat.exists

      when: "'/etc/apt/sources.list.d/elastic-8.x.list' not in (ansible_facts.files | default([]) | map(attribute='path'))"

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
      when: "'apt-transport-https' in ansible_facts.packages | default([])"

    - name: Instalar o Filebeat
      apt:
        name: filebeat
        state: present
      when: "'filebeat' not in ansible_facts.packages | default([])"

    - name: Habilitar o serviço Filebeat
      systemd:
        name: filebeat
        enabled: yes
      when: "'filebeat' in ansible_facts.packages | default([])"

    - name: Configurar inicialização automática do Filebeat
      command: update-rc.d filebeat defaults 95 10
      when: "'filebeat' in ansible_facts.packages | default([])"

    - name: Atualizar lista de pacotes novamente
      apt:
        update_cache: yes
      when: "'filebeat' in ansible_facts.packages | default([])"

    - name: Instalar o Elasticsearch
      apt:
        name: elasticsearch
        state: present
      when: "'elasticsearch' not in ansible_facts.packages | default([])"

